wandb_version: 1

d_ff:
  value: 64
d_layers:
  value: 1
d_model:
  value: 256
dropout:
  value: 0.3
e_layers:
  value: 3
emb_dim:
  value: 32
factor:
  value: 5
learning_rate:
  value: 1.4104001425973598e-06
n_agg:
  value: 8
n_heads:
  value: 8
out_len:
  value: 16
patch_dim:
  value: 24
seed:
  value: 66
