wandb_version: 1

d_ff:
  value: 256
d_layers:
  value: 1
d_model:
  value: 128
dropout:
  value: 0.1
e_layers:
  value: 5
emb_dim:
  value: 128
factor:
  value: 15
learning_rate:
  value: 8.924512822960145e-05
n_agg:
  value: 5
n_heads:
  value: 12
out_len:
  value: 32
patch_dim:
  value: 1
seed:
  value: 66
