wandb_version: 1

d_ff:
  value: 64
d_layers:
  value: 1
d_model:
  value: 1024
dropout:
  value: 0.5
e_layers:
  value: 2
emb_dim:
  value: 48
factor:
  value: 10
learning_rate:
  value: 1.1640413728008111e-05
n_agg:
  value: 2
n_heads:
  value: 4
out_len:
  value: 2
patch_dim:
  value: 6
seed:
  value: 66
