wandb_version: 1

d_ff:
  value: 256
d_layers:
  value: 1
d_model:
  value: 512
dropout:
  value: 0.1
e_layers:
  value: 3
emb_dim:
  value: 128
factor:
  value: 15
learning_rate:
  value: 1.32336628990985e-06
n_agg:
  value: 3
n_heads:
  value: 8
out_len:
  value: 8
patch_dim:
  value: 24
seed:
  value: 66
