wandb_version: 1

d_ff:
  value: 64
d_layers:
  value: 1
d_model:
  value: 64
dropout:
  value: 0.2
e_layers:
  value: 3
emb_dim:
  value: 16
factor:
  value: 5
learning_rate:
  value: 6.923387387649209e-06
n_agg:
  value: 4
n_heads:
  value: 2
out_len:
  value: 8
patch_dim:
  value: 16
seed:
  value: 66
