wandb_version: 1

d_ff:
  value: 256
d_layers:
  value: 0
d_model:
  value: 256
dropout:
  value: 0
e_layers:
  value: 3
emb_dim:
  value: 128
factor:
  value: 10
learning_rate:
  value: 8.80517501733136e-05
n_agg:
  value: 3
n_heads:
  value: 10
out_len:
  value: 4
patch_dim:
  value: 1
seed:
  value: 66
