wandb_version: 1

d_ff:
  value: 1024
d_layers:
  value: 0
d_model:
  value: 64
dropout:
  value: 0.2
e_layers:
  value: 2
emb_dim:
  value: 256
factor:
  value: 5
learning_rate:
  value: 8.391537190643313e-05
n_agg:
  value: 4
n_heads:
  value: 12
out_len:
  value: 16
patch_dim:
  value: 1
seed:
  value: 66
