wandb_version: 1

d_ff:
  value: 128
d_layers:
  value: 1
d_model:
  value: 1024
dropout:
  value: 0
e_layers:
  value: 4
emb_dim:
  value: 320
factor:
  value: 10
learning_rate:
  value: 4.185407967574562e-06
n_agg:
  value: 6
n_heads:
  value: 6
out_len:
  value: 320
patch_dim:
  value: 16
seed:
  value: 66
