wandb_version: 1

d_ff:
  value: 512
d_layers:
  value: 1
d_model:
  value: 64
dropout:
  value: 0.4
e_layers:
  value: 5
emb_dim:
  value: 48
factor:
  value: 5
learning_rate:
  value: 2.756969919850427e-06
n_agg:
  value: 2
n_heads:
  value: 10
out_len:
  value: 16
patch_dim:
  value: 24
seed:
  value: 66
