wandb_version: 1

d_ff:
  value: 128
d_layers:
  value: 1
d_model:
  value: 1024
dropout:
  value: 0
e_layers:
  value: 4
emb_dim:
  value: 128
factor:
  value: 15
learning_rate:
  value: 6.328755798655728e-06
n_agg:
  value: 4
n_heads:
  value: 12
out_len:
  value: 8
patch_dim:
  value: 4
seed:
  value: 66
