wandb_version: 1

d_ff:
  value: 1024
d_layers:
  value: 1
d_model:
  value: 128
dropout:
  value: 0.4
e_layers:
  value: 3
emb_dim:
  value: 320
factor:
  value: 5
learning_rate:
  value: 1.4607365141002088e-05
n_agg:
  value: 5
n_heads:
  value: 6
out_len:
  value: 16
patch_dim:
  value: 2
seed:
  value: 66
