wandb_version: 1

d_ff:
  value: 128
d_layers:
  value: 1
d_model:
  value: 256
dropout:
  value: 0.4
e_layers:
  value: 2
emb_dim:
  value: 32
factor:
  value: 10
learning_rate:
  value: 1.5303518524850115e-06
n_agg:
  value: 6
n_heads:
  value: 6
out_len:
  value: 320
patch_dim:
  value: 2
seed:
  value: 66
