wandb_version: 1

d_ff:
  value: 1024
d_layers:
  value: 1
d_model:
  value: 256
dropout:
  value: 0.5
e_layers:
  value: 2
emb_dim:
  value: 128
factor:
  value: 15
learning_rate:
  value: 2.4921675033001775e-06
n_agg:
  value: 2
n_heads:
  value: 6
out_len:
  value: 2
patch_dim:
  value: 1
seed:
  value: 66
