wandb_version: 1

d_ff:
  value: 128
d_layers:
  value: 1
d_model:
  value: 64
dropout:
  value: 0.1
e_layers:
  value: 5
emb_dim:
  value: 64
factor:
  value: 10
learning_rate:
  value: 5.945964757596035e-06
n_agg:
  value: 3
n_heads:
  value: 10
out_len:
  value: 128
patch_dim:
  value: 2
seed:
  value: 66
