wandb_version: 1

d_ff:
  value: 128
d_layers:
  value: 0
d_model:
  value: 1024
dropout:
  value: 0.5
e_layers:
  value: 2
emb_dim:
  value: 48
factor:
  value: 15
learning_rate:
  value: 1.6065783699581663e-05
n_agg:
  value: 7
n_heads:
  value: 2
out_len:
  value: 4
patch_dim:
  value: 1
seed:
  value: 66
