wandb_version: 1

d_ff:
  value: 128
d_layers:
  value: 0
d_model:
  value: 64
dropout:
  value: 0.5
e_layers:
  value: 4
emb_dim:
  value: 24
factor:
  value: 5
learning_rate:
  value: 7.621350628365941e-06
n_agg:
  value: 7
n_heads:
  value: 2
out_len:
  value: 64
patch_dim:
  value: 8
seed:
  value: 66
